"""Universos de acciones curados por mercado para el Filtro de los Tres Candados.

Cada mercado define su indice de referencia y un universo de valores liquidos
(grandes capitalizaciones de los principales indices regionales). El market cap
es un valor aproximado en divisa local: todos los valores del universo son
mega/large caps, por lo que el Candado 1A se evalua con esta aproximacion sin
necesidad de una llamada extra por ticker (mantiene la API rapida y estable).
Precios y volumenes se descargan SIEMPRE en tiempo real de Yahoo Finance.
"""

B = 1e9  # mil millones (billion)

MERCADOS = {
    "america": {
        "nombre": "América",
        "indice": "^GSPC",
        "nombre_indice": "S&P 500",
        "nota": "Importes en USD.",
        "universo": {
            "AAPL":  {"nombre": "Apple",              "sector": "Tecnología",         "market_cap": 3400 * B},
            "MSFT":  {"nombre": "Microsoft",          "sector": "Tecnología",         "market_cap": 3500 * B},
            "NVDA":  {"nombre": "NVIDIA",             "sector": "Tecnología",         "market_cap": 3400 * B},
            "AVGO":  {"nombre": "Broadcom",           "sector": "Tecnología",         "market_cap": 1100 * B},
            "AMD":   {"nombre": "AMD",                "sector": "Tecnología",         "market_cap": 250 * B},
            "GOOGL": {"nombre": "Alphabet",           "sector": "Comunicaciones",     "market_cap": 2300 * B},
            "META":  {"nombre": "Meta Platforms",     "sector": "Comunicaciones",     "market_cap": 1500 * B},
            "NFLX":  {"nombre": "Netflix",            "sector": "Comunicaciones",     "market_cap": 500 * B},
            "DIS":   {"nombre": "Disney",             "sector": "Comunicaciones",     "market_cap": 200 * B},
            "AMZN":  {"nombre": "Amazon",             "sector": "Consumo Cíclico",    "market_cap": 2300 * B},
            "TSLA":  {"nombre": "Tesla",              "sector": "Consumo Cíclico",    "market_cap": 1000 * B},
            "HD":    {"nombre": "Home Depot",         "sector": "Consumo Cíclico",    "market_cap": 360 * B},
            "JPM":   {"nombre": "JPMorgan Chase",     "sector": "Financiero",         "market_cap": 700 * B},
            "V":     {"nombre": "Visa",               "sector": "Financiero",         "market_cap": 650 * B},
            "MA":    {"nombre": "Mastercard",         "sector": "Financiero",         "market_cap": 500 * B},
            "BRK-B": {"nombre": "Berkshire Hathaway", "sector": "Financiero",         "market_cap": 1000 * B},
            "LLY":   {"nombre": "Eli Lilly",          "sector": "Salud",              "market_cap": 800 * B},
            "UNH":   {"nombre": "UnitedHealth",       "sector": "Salud",              "market_cap": 350 * B},
            "JNJ":   {"nombre": "Johnson & Johnson",  "sector": "Salud",              "market_cap": 380 * B},
            "MRK":   {"nombre": "Merck",              "sector": "Salud",              "market_cap": 250 * B},
            "XOM":   {"nombre": "Exxon Mobil",        "sector": "Energía",            "market_cap": 480 * B},
            "CVX":   {"nombre": "Chevron",            "sector": "Energía",            "market_cap": 280 * B},
            "WMT":   {"nombre": "Walmart",            "sector": "Consumo Defensivo",  "market_cap": 750 * B},
            "COST":  {"nombre": "Costco",             "sector": "Consumo Defensivo",  "market_cap": 400 * B},
            "PG":    {"nombre": "Procter & Gamble",   "sector": "Consumo Defensivo",  "market_cap": 400 * B},
            "KO":    {"nombre": "Coca-Cola",          "sector": "Consumo Defensivo",  "market_cap": 290 * B},
            "CAT":   {"nombre": "Caterpillar",        "sector": "Industriales",       "market_cap": 180 * B},
            "GE":    {"nombre": "GE Aerospace",       "sector": "Industriales",       "market_cap": 250 * B},
            "BA":    {"nombre": "Boeing",             "sector": "Industriales",       "market_cap": 130 * B},
        },
    },
    "europa": {
        "nombre": "Europa",
        "indice": "^STOXX50E",
        "nombre_indice": "EURO STOXX 50",
        "nota": "Importes en divisa local (EUR, CHF, GBp).",
        "universo": {
            "ASML.AS":  {"nombre": "ASML",             "sector": "Tecnología",        "market_cap": 350 * B},
            "SAP.DE":   {"nombre": "SAP",              "sector": "Tecnología",        "market_cap": 280 * B},
            "MC.PA":    {"nombre": "LVMH",             "sector": "Consumo Cíclico",   "market_cap": 320 * B},
            "RMS.PA":   {"nombre": "Hermès",           "sector": "Consumo Cíclico",   "market_cap": 230 * B},
            "ITX.MC":   {"nombre": "Inditex",          "sector": "Consumo Cíclico",   "market_cap": 150 * B},
            "OR.PA":    {"nombre": "L'Oréal",          "sector": "Consumo Defensivo", "market_cap": 200 * B},
            "NESN.SW":  {"nombre": "Nestlé",           "sector": "Consumo Defensivo", "market_cap": 210 * B},
            "ULVR.L":   {"nombre": "Unilever",         "sector": "Consumo Defensivo", "market_cap": 110 * B},
            "TTE.PA":   {"nombre": "TotalEnergies",    "sector": "Energía",           "market_cap": 140 * B},
            "SHEL.L":   {"nombre": "Shell",            "sector": "Energía",           "market_cap": 160 * B},
            "SAN.PA":   {"nombre": "Sanofi",           "sector": "Salud",             "market_cap": 120 * B},
            "NOVN.SW":  {"nombre": "Novartis",         "sector": "Salud",             "market_cap": 200 * B},
            "ROG.SW":   {"nombre": "Roche",            "sector": "Salud",             "market_cap": 230 * B},
            "AZN.L":    {"nombre": "AstraZeneca",      "sector": "Salud",             "market_cap": 180 * B},
            "AIR.PA":   {"nombre": "Airbus",           "sector": "Industriales",      "market_cap": 130 * B},
            "SU.PA":    {"nombre": "Schneider Electric", "sector": "Industriales",    "market_cap": 130 * B},
            "SIE.DE":   {"nombre": "Siemens",          "sector": "Industriales",      "market_cap": 180 * B},
            "ALV.DE":   {"nombre": "Allianz",          "sector": "Financiero",        "market_cap": 130 * B},
            "SAN.MC":   {"nombre": "Banco Santander",  "sector": "Financiero",        "market_cap": 100 * B},
            "BNP.PA":   {"nombre": "BNP Paribas",      "sector": "Financiero",        "market_cap": 75 * B},
            "ISP.MI":   {"nombre": "Intesa Sanpaolo",  "sector": "Financiero",        "market_cap": 80 * B},
            "HSBA.L":   {"nombre": "HSBC",             "sector": "Financiero",        "market_cap": 160 * B},
            "DTE.DE":   {"nombre": "Deutsche Telekom", "sector": "Comunicaciones",    "market_cap": 150 * B},
            "IBE.MC":   {"nombre": "Iberdrola",        "sector": "Servicios Públicos", "market_cap": 95 * B},
            "ENEL.MI":  {"nombre": "Enel",             "sector": "Servicios Públicos", "market_cap": 75 * B},
        },
    },
    "asia": {
        "nombre": "Asia",
        "indice": "^N225",
        "nombre_indice": "Nikkei 225",
        "nota": "Importes en divisa local (JPY, HKD, KRW, TWD).",
        "universo": {
            "7203.T":    {"nombre": "Toyota",          "sector": "Consumo Cíclico",  "market_cap": 45000 * B},
            "9983.T":    {"nombre": "Fast Retailing",  "sector": "Consumo Cíclico",  "market_cap": 15000 * B},
            "6758.T":    {"nombre": "Sony",            "sector": "Tecnología",       "market_cap": 22000 * B},
            "6861.T":    {"nombre": "Keyence",         "sector": "Tecnología",       "market_cap": 15000 * B},
            "8035.T":    {"nombre": "Tokyo Electron",  "sector": "Tecnología",       "market_cap": 12000 * B},
            "6501.T":    {"nombre": "Hitachi",         "sector": "Industriales",     "market_cap": 18000 * B},
            "8306.T":    {"nombre": "Mitsubishi UFJ",  "sector": "Financiero",       "market_cap": 22000 * B},
            "9984.T":    {"nombre": "SoftBank Group",  "sector": "Comunicaciones",   "market_cap": 16000 * B},
            "7974.T":    {"nombre": "Nintendo",        "sector": "Comunicaciones",   "market_cap": 13000 * B},
            "4063.T":    {"nombre": "Shin-Etsu Chemical", "sector": "Materiales",    "market_cap": 10000 * B},
            "0700.HK":   {"nombre": "Tencent",         "sector": "Comunicaciones",   "market_cap": 4500 * B},
            "9988.HK":   {"nombre": "Alibaba",         "sector": "Consumo Cíclico",  "market_cap": 2300 * B},
            "3690.HK":   {"nombre": "Meituan",         "sector": "Consumo Cíclico",  "market_cap": 800 * B},
            "9618.HK":   {"nombre": "JD.com",          "sector": "Consumo Cíclico",  "market_cap": 400 * B},
            "1810.HK":   {"nombre": "Xiaomi",          "sector": "Tecnología",       "market_cap": 1300 * B},
            "1299.HK":   {"nombre": "AIA Group",       "sector": "Financiero",       "market_cap": 700 * B},
            "0005.HK":   {"nombre": "HSBC (HK)",       "sector": "Financiero",       "market_cap": 1700 * B},
            "0941.HK":   {"nombre": "China Mobile",    "sector": "Comunicaciones",   "market_cap": 1600 * B},
            "005930.KS": {"nombre": "Samsung Electronics", "sector": "Tecnología",   "market_cap": 400000 * B},
            "000660.KS": {"nombre": "SK Hynix",        "sector": "Tecnología",       "market_cap": 150000 * B},
            "2330.TW":   {"nombre": "TSMC",            "sector": "Tecnología",       "market_cap": 25000 * B},
            "2317.TW":   {"nombre": "Hon Hai (Foxconn)", "sector": "Tecnología",     "market_cap": 2500 * B},
        },
    },
}
